### PR TITLE
Explain how to prepare a patch, and give instructions to install and regstrap GCC the first time.

### PR DESCRIPTION
**Pull request by vultkayn**
Hi David,

I had these updates in some dark corner of my pc, I've adjusted it and added some stuff during
my latest regstrapping frenzy.

If anything is amiss, please tell me so.
I have checked it compiles with make html on my box, and I hope there are not too many misspelled words.

I sometimes went with a humorous tone. Maybe I shouldn't have, I don't know.
I'll wait for your feedback.

Cheers,
Benjamin.

### CODE REVIEW

**Comment by davidmalcolm** [comment]
Hi Benjamin

Overall, looks  great - thanks!

I'm hoping to merge these docs into GCC's source tree, as an official tutorial for new GCC contributors. To that end, as of 8f6ab488330da35744d940b067f84bddda6fd121 I've licensed these docs under "GPLv3 or later".  

@vultkayn: please can you either:

- add such a license header to your new file, or
- clearly state here that your contribution is licensed under GPLv3 or later

Thanks

**Comment by vultkayn** [comment]
Dear David,

Feel free to add GPLv3+ license as you see fit

**Comment by davidmalcolm** [comment]
Thanks!  I've rebased the patches and pushed them.

**Comment by vultkayn** [comment]
Great, thanks Dave!

**Pull request closed without merging**
